media:
  - name: media
    label: Images and Video
    input: uploads
    output: /uploads
    rename: safe
    categories:
      - image
      - video
      - audio
    actions:
      - name: optimize-images
        label: Optimize Images
        workflow: pages-cms-optimize-images.yml
    commit:
      templates:
        create: "media: add {filename}"
        update: "media: update {filename}"
        delete: "media: remove {filename}"
        rename: "media: rename {oldFilename} -> {newFilename}"
  - name: docs
    label: Documents
    input: uploads/docs
    output: /uploads/docs
    rename: safe
    categories:
      - document
      - spreadsheet
      - code
    commit:
      templates:
        create: "docs: add {filename}"
        update: "docs: update {filename}"
        delete: "docs: remove {filename}"
        rename: "docs: rename {oldFilename} -> {newFilename}"

content:
  - name: posts
    label: Posts
    type: group
    items:
    - name: links
      label: Links
      type: collection
      path: _posts/links
      fields:
        - name: layout
          type: string
          default: post
          hidden: true
        - name: title
          label: Title
          type: string
        - name: body
          label: Body
          type: rich-text
          options:
            format: markdown
            media: media
        - name: external_url
          label: Link
          type: string
        - name: reaction
          label: Reaction
          type: select
          options:
            placeholder: Choose an IndieWeb-compatible reaction
            values:
              - name: reply
                label: Reply
              - name: like
                label: Like
              - name: repost
                label: Repost
        - name: date
          label: Date
          type: date
          options:
            time: true
            format: yyyy-MM-dd' 'HH:mm' -0300'
        - name: category
          type: string
          default: links
          hidden: true
        - name: tags
          label: Tags
          type: string
          list: true
