# Site Settings
title: "Irrelefante"
description: >-
  Por Arthur Freitas.
  
url: "https://irrelefante.com.br"
baseurl: ""

author:
  name: Arthur Freitas
  url: "https://arthr.me"
  twitter: "@arthrfrts"

collections:
  notes:
    output: true
    permalink: /:slug

# Build Settings
incremental: true
permalink: pretty
relative_permalinks: false

plugins:
  - jekyll-last-modified-at

sass:
  dir: _sass
  style: :compressed

include:
  - _pages
exclude:
  - _includes/notes_graph.json
  
defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
  
# 🌱 Settings
use_html_extension: false
open_external_links_in_new_tab: true
embed_tweets: false