# Site settings
title: Irrelefante
description: >-
  Nada faz muito sentido.

lang: pt-br  

baseurl: ""
url: "https://irrelefante.com.br"

# Build settings
theme: linus

paginate: 10
permalink: /:slugified_categories/:year-:month-:title:output_ext

category_colors:
  - name: Impressões
    color: '#eba07d'
  - name: Esquinas
    color: '#a0c46e'
  - name: Achados
    color: '#82bbcf'
  - name: Listas
    color: '#e6b855'
    
logo: /assets/favicon.png

plugins:
  - jekyll-webmention_io
  - jekyll-standard-site
  
webmentions:
  username: arthr.me
  cache_folder: .cache
  cache_bad_uris_for: 5
  legacy_domains:
    - https://arthr.me

seo:
  name: Irrelefante
  links:
    - https://arthr.me/
    - https://github.com/arthrfrts
    - https://bsky.app/profile/arthr.me

standard_site:
  publication: "at://did:plc:aeaouj6eedwqmk4z3pies55n/site.standard.publication/3mo7dptc3bi2t"