name: Optimize Images

on:
  workflow_dispatch:
    inputs:
      payload:
        description: Pages CMS payload
        required: true
        type: string
  push:
    paths:
      - 'uploads/**'

jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compress Images
        uses: calibreapp/image-actions@main
